/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about/About.vue')['default']
    Accordion: typeof import('./src/components/base/Accordion.vue')['default']
    Bottompage: typeof import('./src/components/bottompage/Bottompage.vue')['default']
    Comparison: typeof import('./src/components/home/Comparison.vue')['default']
    Content: typeof import('./src/components/uploadhome/Content.vue')['default']
    ContentHistory: typeof import('./src/components/uploadhome/ContentHistory.vue')['default']
    copy: typeof import('./src/components/Uploadhome/Content copy.vue')['default']
    Dialog: typeof import('./src/components/home/Dialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    HeaderSection: typeof import('./src/components/header/HeaderSection.vue')['default']
    Hero: typeof import('./src/components/home/Hero.vue')['default']
    HomeMain: typeof import('./src/components/uploadhome/HomeMain.vue')['default']
    ImpactThatMatters: typeof import('./src/components/home/ImpactThatMatters.vue')['default']
    KeyFeatures: typeof import('./src/components/home/KeyFeatures.vue')['default']
    LogoStripe: typeof import('./src/components/home/LogoStripe.vue')['default']
    Marquee: typeof import('./src/components/base/Marquee.vue')['default']
    NowInfoPage: typeof import('./src/components/uploadhome/NowInfoPage.vue')['default']
    Research: typeof import('./src/components/research/Research.vue')['default']
    Resource: typeof import('./src/components/home/Resource.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeLine: typeof import('./src/components/base/timeLine.vue')['default']
    Uppage: typeof import('./src/components/uppage/Uppage.vue')['default']
  }
}
