/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/base/Accordion.vue')['default']
    Bottompage: typeof import('./src/components/bottompage/Bottompage.vue')['default']
    Content: typeof import('./src/components/uploadhome/Content.vue')['default']
    ContentHistory: typeof import('./src/components/uploadhome/ContentHistory.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    HeaderSection: typeof import('./src/components/header/HeaderSection.vue')['default']
    HomeMain: typeof import('./src/components/uploadhome/HomeMain.vue')['default']
    NowInfoPage: typeof import('./src/components/uploadhome/NowInfoPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeLine: typeof import('./src/components/base/timeLine.vue')['default']
    Uppage: typeof import('./src/components/uppage/Uppage.vue')['default']
  }
}
